cybersource:
  access_key: SET-ME-PLEASE
  cancel_checkout_path: /checkout/cancel-checkout/
  merchant_id: SET-ME-PLEASE
  payment_page_url: https://testsecureacceptance.cybersource.com/pay
  profile_id: SET-ME-PLEASE
  receipt_page_url: /checkout/receipt/
  secret_key: SET-ME-PLEASE
  send_level_2_3_details: true
  soap_api_url: https://ics2wstest.ic3.com/commerce/1.x/transactionProcessor/CyberSourceTransaction_1.140.wsdl
  sop_access_key: SET-ME-PLEASE
  sop_payment_page_url: https://testsecureacceptance.cybersource.com/silent/pay
  sop_profile_id: SET-ME-PLEASE
  sop_secret_key: SET-ME-PLEASE
  transaction_key: SET-ME-PLEASE
paypal:
  cancel_checkout_path: /checkout/cancel-checkout/
  client_id: AaWy7_yAjbtKwmYWf5pbCSR9lBLWREhwZ4RMh0TWppo2hSwWi5pI7oXgsKDr3DEVzmvpi2YWv4BI2E1z
  client_secret: ELBEgeFs7Clhmceaw_LDboJt3vrOYQ5g9O8TWjrxm1RFcq6bFBMV6QBGDR0vRAExfPE6WshCFtteo89I
  error_url: /checkout/error/
  mode: sandbox
  receipt_url: /checkout/receipt/
